window:
  padding:
    x: 5
    y: 5
  dynamic_padding: true

scrolling:
  history: 1000
  multiplier: 3

font:
  normal:
    family: JetBrains Mono
  bold:
    family: JetBrains Mono
  italic:
    family: JetBrains Mono
  size: 14

schemes:
  paper: &paper
    primary:
      background: '#f2eede'
      foreground: '#000000'
    normal:
      black:   '#000000'
      red:     '#cc3e28'
      green:   '#216609'
      yellow:  '#b58900'
      blue:    '#1e6fcc'
      magenta: '#5c21a5'
      cyan:    '#158c86'
      white:   '#aaaaaa'
    bright:
      black:   '#555555'
      red:     '#cc3e28'
      green:   '#216609'
      yellow:  '#b58900'
      blue:    '#1e6fcc'
      magenta: '#5c21a5'
      cyan:    '#158c86'
      white:   '#aaaaaa'

  tokyo-night-storm: &tokyo-night-storm
    primary:
      background: '0x24283b'
      foreground: '0xa9b1d6'
    normal:
      black:   '0x32344a'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xad8ee6'
      cyan:    '0x449dab'
      white:   '0x9699a8'
    bright:
      black:   '0x444b6a'
      red:     '0xff7a93'
      green:   '0xb9f27c'
      yellow:  '0xff9e64'
      blue:    '0x7da6ff'
      magenta: '0xbb9af7'
      cyan:    '0x0db9d7'
      white:   '0xacb0d0'

colors: *paper

key_bindings:
    - { key: N,   mods: Control|Shift, action: SpawnNewInstance }
